package config

import (
	"testing"
)

func TestLoad_DefaultsApplied(t *testing.T) {
	t.Setenv("PICOORACLAW_URL", "")
	t.Setenv("PICOORACLAW_WEBUI_LISTEN", "")
	cfg, err := Load([]string{})
	if err != nil {
		t.Fatal(err)
	}
	if cfg.PicooraclawURL != "http://localhost:8090" {
		t.Fatalf("default url: %q", cfg.PicooraclawURL)
	}
	if cfg.Listen != ":3000" {
		t.Fatalf("default listen: %q", cfg.Listen)
	}
}

func TestLoad_EnvOverridesDefault(t *testing.T) {
	t.Setenv("PICOORACLAW_URL", "http://1.2.3.4:9000")
	cfg, _ := Load([]string{})
	if cfg.PicooraclawURL != "http://1.2.3.4:9000" {
		t.Fatalf("env not applied: %q", cfg.PicooraclawURL)
	}
}

func TestLoad_FlagOverridesEnv(t *testing.T) {
	t.Setenv("PICOORACLAW_URL", "http://env:9000")
	cfg, _ := Load([]string{"--picooraclaw-url", "http://flag:9000"})
	if cfg.PicooraclawURL != "http://flag:9000" {
		t.Fatalf("flag not applied: %q", cfg.PicooraclawURL)
	}
}

func TestLoad_SecretAutoGenerated(t *testing.T) {
	t.Setenv("PICOORACLAW_WEBUI_SECRET", "")
	cfg, err := Load([]string{})
	if err != nil {
		t.Fatal(err)
	}
	if len(cfg.Secret) != 64 { // 32 bytes → 64 hex chars
		t.Fatalf("secret not generated (len=%d): %q", len(cfg.Secret), cfg.Secret)
	}
}
